dist: bionic
language: python
python:
  - "3.10"
  - "3.11"
  - "3.12"
  - "3.13"
install:
  - "sudo apt-get install pandoc"
  - "pip install tox-travis uv --upgrade"
  - "uv sync"
script: "uv run poe tox"
