# Use tox-gh to test against multiple python versions concurrently

name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Tests for ${{ matrix.env }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        env:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3

      - name: Install package
        run: uv sync

      - name: Run tests
        run: uv run poe test
